package constants

type HueError int
const (
	UNAUTHORIZED HueError = 1
	INVALID_JSON HueError = 2
	NOT_FOUND HueError = 3
	METHOD_NOT_AVAILABLE HueError = 4
	MISSING_PARAMETERS HueError = 5
	PARAMETER_UNAVAILABLE HueError = 6
	INVALID_PARAMETER_VALUE HueError = 7
	PARAMETER_NOT_MODIFIABLE HueError = 8
	TOO_MANY_ITEMS HueError = 9
	PORTAL_CONNECTION_REQUIRED HueError = 10
	INTERNAL_ERROR HueError = 901
)
